CREATE ROLE root WITH LOGIN PASSWORD 'passwd';

CREATE ROLE rootuser WITH LOGIN PASSWORD 'rootuser' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE DATABASE users_database;
GRANT ALL PRIVILEGES ON DATABASE users_database TO rootuser ;
GRANT ALL PRIVILEGES ON DATABASE users_database TO root;

CREATE ROLE rootaccount WITH LOGIN PASSWORD 'rootaccount' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE DATABASE accounts_database;
GRANT ALL PRIVILEGES ON DATABASE accounts_database TO rootaccount;
GRANT ALL PRIVILEGES ON DATABASE accounts_database TO root;

CREATE ROLE roottransactions WITH LOGIN PASSWORD 'roottransactions' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE DATABASE transactions_database;
GRANT ALL PRIVILEGES ON DATABASE transactions_database TO roottransactions;
GRANT ALL PRIVILEGES ON DATABASE transactions_database TO root;