global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'bankusers'
    scrape_interval: 5s
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['localhost:8081']
#  - job_name: 'transaction'
#    scrape_interval: 5s
#    metrics_path: '/q/metrics'
#    static_configs:
#      - targets: ['localhost:8082']
#  - job_name: 'user'
#    scrape_interval: 5s
#    metrics_path: '/q/metrics'
#    static_configs:
#      - targets: ['localhost:8083']
